version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: check current working directory
          command: pwd
      - continuation/continue:
          configuration_path: ./dynamic-config-test/config.yml

workflows:
  setup:
    jobs:
      - setup
